services:
  - type: web
    name: hustle-to-the-quiz
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: QUIZ_ADMIN_ID
        sync: false
      - key: QUIZ_ADMIN_PASSWORD
        sync: false
